flashcards/urls.py
from django.urls import path

from django.contrib.auth import views as auth_views
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static
from . import views

from django.urls import path

from .views import *

app_name = "flashcards"

urlpatterns = [
     
    path('flashcards/', views.flashcards_home, name='flashcards_home'),

    path('flashcards/create_deck/', views.create_deck, name='create_deck'),

    path('flashcards/view/<int:deck_id>/', views.view_deck, name='view_deck'),

    path('flashcards/add_notes/<int:deck_id>/', views.add_notes, name='add_notes'),

    path('flashcards/<int:deck_id>/edit/', views.edit_deck, name='edit_deck'),

    path('flashcards/create_card/<int:deck_id>/', views.create_card, name='create_card'),

    path('flashcards/edit_card/<int:card_id>/', views.edit_card, name='edit_card'),

    path('flashcards/edit_note/<int:note_id>/', views.edit_note, name='edit_note'),

    path('flashcards/profile/<int:user_pk>/', views.user_profile_view, name='user_profile'),

    path('flashcards/about', views.about_us, name='about_us'),

    path('flashcards/clep', views.clep_resources, name='clep'),

    path('flashcards/logout', auth_views.LogoutView.as_view(), name='logout'),

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home_page/urls.py
from django.urls import path, include


from django.contrib.auth import views as auth_views
from django.contrib import admin

from django.conf.urls.static import static
from django.conf import settings

from . import views

app_name='home_page'

urlpatterns = [
    path("", views.home, name="home_page"),
    

    
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profiles/urls.py
from django.urls import path, include

from . import views

app_name='profiles'

urlpatterns=[

     path('user_profile/', views.user_profile, name='User_Profile'),

     path('login/', views.login_the_user, name='login'),

     path('register/', views.registration, name='register'),

     

]

theappdepo/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static



urlpatterns=[
     
    path("", include("home_page.urls")),
     
    path('', include('profiles.urls')),

    path('', include('experimental_playground.urls')),

    path('', include("ilovecookbooks.urls")),

    path('', include("flashcards.urls")),


     path('admin/',admin.site.urls),

     path('accounts/', include('django.contrib.auth.urls')),

     path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),

     path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),

     path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_done'),

     path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

     path('logout', auth_views.LogoutView.as_view(), name='logout'),

     

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

flashcards/models.py
import secrets

import string

from django.contrib.auth.models import AbstractUser, Group, Permission

from django.db import models

from django.contrib.auth import get_user_model

User=get_user_model()




class Deck(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)

    title = models.CharField(max_length=200)

    description = models.TextField()  # Text field instead of ImageField

    public= models.BooleanField(default=False)

    CATEGORY_CHOICES=[

        ('Science','Science'),
        ('Technology','Technology'),
        ('Engineering','Engineering'),
        ('Mathematics','Mathematics'),
        ('History','History'),
        ('Literature','Literature'),
        ('Languages','Languages'),
        ('Arts','Arts'),
        ('Health and Medicine','Health & Medicine'),
        ('Programming','Programming'),
        ('Lifeskills','Lifeskills/Self Help'),
        ('CLEP', 'CLEP Exams'),
        ('Misc','Misc.'),
        
    ]

    category= models.CharField(max_length=25, default='Misc', choices=CATEGORY_CHOICES)



    def __str__(self):

        return self.title
    




from django.utils import timezone

from django.db.models.signals import pre_delete

from django.dispatch import receiver



class Note(models.Model):

    deck = models.ForeignKey(Deck, on_delete=models.CASCADE)

    user = models.ForeignKey(User, on_delete=models.CASCADE)

    note = models.TextField()

    date = models.DateTimeField(default=timezone.now())

    title = models.CharField(max_length=255, blank=True, null=True)



    def save(self, *args, **kwargs):

        if not self.pk:  # Only update on new note creation

            note_count_in_deck = Note.objects.filter(deck=self.deck).count() + 1

            self.title = f"Note {note_count_in_deck} of {self.deck.title}"

        super().save(*args, **kwargs)



    def __str__(self):

        return self.title



@receiver(pre_delete, sender=Note)

def update_note_titles_on_delete(sender, instance, **kwargs):

    remaining_notes = Note.objects.filter(deck=instance.deck).exclude(pk=instance.pk).order_by('pk')

    for index, note in enumerate(remaining_notes, start=1):

        note.title = f"Note {index} of {note.deck.title}"

        note.save()









class Card(models.Model):


    deck = models.ForeignKey(Deck, on_delete=models.CASCADE)

    question = models.TextField()

    answer = models.TextField() 


    def __str__(self):

        return f"Card {self.pk} of {self.deck.title}"
    

class WebImgs(models.Model):

    title= models.CharField(max_length=32,blank=True)

    image= models.ImageField(upload_to='flashcards_web_imgs')

    def save(self, *args, **kwargs):

        super().save(*args, **kwargs)



class Contact(models.Model):

    name = models.CharField(max_length=100)

    email = models.EmailField()

    message = models.TextField()

    current_date = models.DateTimeField(auto_now_add=True)

flashcards/forms.py
from django import forms

from .models import *



class DeckForm(forms.ModelForm):

    class Meta:

        model = Deck

        fields = ['title','description', 'category','public']

        widgets = {

            'public': forms.CheckboxInput(), 

        }


class NoteForm(forms.ModelForm):

        class Meta:

            model = Note

            fields = ['note']

            widgets={
                'note':
                forms.Textarea(attrs={'rows':15})
            }

class CardForm(forms.ModelForm):

    class Meta:

        model = Card

        fields = ['question', 'answer']


class DeleteDeckForm(forms.Form):

    deck_id = forms.IntegerField(widget=forms.HiddenInput)

class DeleteCardForm(forms.Form):

    card_id = forms.IntegerField(widget=forms.HiddenInput)



    

flashcards/views.py
from django.views.generic import ListView, DetailView
from django.views import generic
from django.urls import reverse_lazy
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect, get_object_or_404, HttpResponseRedirect
from django.core.mail import send_mail
from django.conf import settings
from django.views import View 
from .models import Deck, Card,WebImgs, Contact,Note
from django.http import HttpResponse
from django.http import HttpResponseForbidden
from django.contrib.auth.decorators import login_required
from .forms import DeckForm, CardForm, DeleteCardForm, DeleteDeckForm,NoteForm
from collections import OrderedDict
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User

from django.contrib import messages

from django.urls import reverse


User = get_user_model()



def flashcards_home(request):

    """_____I imported OrderedDict and created an instance of a dictionary of the Deck.Category choices
    _____It sorts by the id # so I had to call lambda function and key[1] is used because the keywords 
    _____are in that column. So basically this is how to sort your items by the category choices defined
    _____in the model's category dictionary.

    """

    user_decks = Deck.objects.all()

    public_decks_by_category = {}

    category_choices_dict = dict(Deck.CATEGORY_CHOICES)

    sorted_categories = OrderedDict(sorted(category_choices_dict.items(), key=lambda key: key[1]))

    for category in sorted_categories.keys():

        public_decks_by_category[category] = Deck.objects.filter(public=True, category=category).order_by('category')


    return render(request, 'flashcards_home.html', {

        'user_decks': user_decks,

        'public_decks_by_category': public_decks_by_category,

    })


def user_profile_view(request, user_pk):

    user = get_object_or_404(User, pk=user_pk)

    user_decks = Deck.objects.filter(user=user)



    if request.method == 'POST':

        for deck in user_decks:

            public_checkbox_name = f'public_{deck.id}'

            if public_checkbox_name in request.POST:

                deck.public = True

            else:

                deck.public = False

            deck.save()

    




    return render(request, 'flashcards_user_profile.html', {'user_decks': user_decks, 'user':user})


@login_required

def create_deck(request):

    """
    Imported this Deck Form so users can have a view to create new decks
    """

    if request.method == 'POST':
        

            user = request.user

            user_decks_count = Deck.objects.filter(user=user).count()


            if user.is_verified == 'N' and user_decks_count >= 5:

                print('MAX LIMIT REACHED FOR UNAUTH USER')

                return redirect('home')


            if user.is_verified == 'Y' and user_decks_count >= 20:

                print("MAX LIMIT REACHED FOR AUTH USER")

                return redirect('flashcards:user_profile', user_pk=request.user.pk)



            form = DeckForm(request.POST)

            if form.is_valid():

                deck = form.save(commit=False)

                deck.user = request.user

                deck.save()

            return redirect('flashcards:user_profile', user_pk=request.user.pk)

    else:

        form = DeckForm()

    return render(request, 'create_deck.html', {'form': form})



####################################

@login_required

def add_notes(request, deck_id):

    deck = get_object_or_404(Deck, id=deck_id)



    # Check if the user is the owner of the deck

    if request.user == deck.user:

        if request.method == 'POST':

            form = NoteForm(request.POST)

            if form.is_valid():

                print("form is valid")

                notes = form.cleaned_data['note']

                Note.objects.create(deck=deck,user=request.user, note=notes)

                messages.success(request, 'Notes added successfully!')

                return redirect('flashcards:view_deck', deck_id=deck.id)

        else:

            form = NoteForm()



        return render(request, 'add_notes.html', {'form': form, 'deck': deck})
    
    else:

        messages.error(request, 'You do not have permission to add notes to this deck.')

        return redirect('view_deck', deck_id=deck.id)

##################################

def view_deck(request, deck_id):

    deck = get_object_or_404(Deck, id=deck_id)

    #will need this for production for fix images' paths

    cloudfront_url="https://d17usxoyp786nd.cloudfront.net/"

    images=WebImgs.objects.all()

    flip_button=images[1]

    left=images[0]

    right=images[2]

    flashcard=images[3]

    back=images[4]

    notes = Note.objects.filter(deck=deck)

    cards = Card.objects.filter(deck=deck)



    if request.method == 'POST':

        delete_card_form = DeleteCardForm(request.POST)

        if delete_card_form.is_valid():

            card_id = delete_card_form.cleaned_data['card_id']

            card_to_delete = get_object_or_404(Card, id=card_id, deck=deck)

            card_to_delete.delete()


        return redirect('view_deck', deck_id=deck.id)

    else:

        delete_card_form = DeleteCardForm()



    return render(request, 'view_deck.html', {'deck': deck, 'cards': cards, 'delete_card_form': delete_card_form, 'flip_button':flip_button, 'left':left,'right': right,'flashcard':flashcard, 'back':back, 'notes':notes})

@login_required

def create_card(request, deck_id):

    deck = Deck.objects.get(id=deck_id)

    if request.method == 'POST':

        user = request.user


        user_card_count = Card.objects.filter(deck__user=user).count()


        if user.is_verified == 'N' and user_card_count >= 250:

                return redirect('flashcards_home')



        if user.is_verified == 'Y' and user_card_count >= 2000:


                return redirect('flashcards:user_profile', user_pk=request.user.pk)
        

        form = CardForm(request.POST)

        if form.is_valid():

            card = form.save(commit=False)

            card.deck = deck

            card.save()

            return redirect('flashcards:view_deck', deck_id=deck.id)

    else:

        form = CardForm()

    return render(request, 'create_card.html', {'form': form, 'deck': deck})



#####################  EDIT CARDS, NOTES, AND DECK ##################


@login_required

def edit_card(request, card_id):

       card = get_object_or_404(Card, id=card_id, deck__user=request.user)

       if request.method == 'POST':

           form = CardForm(request.POST, instance=card)

           if form.is_valid():

               form.save()

               return redirect('view_deck', deck_id=card.deck.id)

       else:

           form = CardForm(instance=card)

       return render(request, 'edit_card.html', {'form': form, 'card': card})



@login_required

def edit_note(request, note_id):

       note = get_object_or_404(Note, id=note_id, user=request.user)

       if request.method == 'POST':

           form = NoteForm(request.POST, instance=note)

           if form.is_valid():

               form.save()

               return redirect('flashcards:view_deck', deck_id=note.deck.id)

       else:

           form = NoteForm(instance=note)

       return render(request, 'edit_note.html', {'form': form, 'note': note})




def edit_deck(request, deck_id):

    deck = get_object_or_404(Deck, id=deck_id)



    if request.method == 'POST':

            form = DeckForm(request.POST, instance=deck)

            delete_form = DeleteDeckForm(request.POST)



            if delete_form.is_valid():

                deck.delete()

                return redirect('flashcards:user_profile', user_pk=request.user.pk)



            if form.is_valid():

                deck_instance = form.save(commit=False)

                deck_instance.public = request.POST.get('public', False) == 'on'

                deck_instance.save()

                return redirect('flashcards:view_deck', deck_id=deck_id)

    else:

            form = DeckForm(instance=deck)

            delete_form = DeleteDeckForm(initial={'deck_id': deck_id})



    return render(request, 'edit_deck.html', {'form': form, 'delete_deck_form': delete_form, 'deck': deck})


def about_us(request):

    print("about us triggered")

    return render(request, 'flashcards:about_us.html')


def clep_resources(request):

    print("clep_resources")

    return render(request, 'flashcards:clep_resources.html')

templates/flashcards/Error.html
<!DOCTYPE html>
<html lang="en">
<head>
     <meta charset="UTF-8">
     <meta http-equiv="X-UA-Compatible" content="IE=edge">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <title>Document</title>
</head>

<body>
     <h1>We're Sorry!</h1>
     <p>There was an error.</p>

     <a href="{% url 'flashcards:flashcards_home' %}">Go Home</a>
</body>
</html>

templates/flashcards/about_us.html
<!DOCTYPE html>
<html lang="en">
<head>
     <meta charset="UTF-8">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">

     {%load static%}
     <link rel="stylesheet" type="text/css" href="{% static 'flashcards/css.css' %}">


     <title>Document</title>
</head>
<body>

     <div class="text-container">
 
          <h1>About Us</h1>
  
      </div>

      <div class="main-content">

          <nav>
      
            <div class="row">

      
            <a href="{% url 'flashcards:flashcards_home' %}">Home</a>
            </div>

          </nav>

     </div>

     
     <div class="text-container2">

          <h3>Mission Statement</h3>
      
          <p>I dream of a future where education is free for anyone who wants to learn. I have also laid out a step by step plan for getting college credits paid for here <a href="{% url 'clep'%}">CLEP info</a> </p>
          
          
     </div>
     
     
     <div class="text-container3">
     <p>I hope this website will grow into an education sharing platform. I will continue to add features that will help with learning. Some of the things I have in mind are:</p>

           
     <ul>

          <li><p>Adding a note taking word processor.</p></li>
          <li><p>A practice test generator</p></li>
          <li><p>and I want to add a GPT plugin to generate flash cards.</p></li>
          <li><p>If I monetize this, it will be on a donation basis. So don't worry, I will never demand money for service.</p></li>

     </ul>

      
      </div>

     
</body>
</html>

templates/flashcards/add_notes.html
<!DOCTYPE html>
<html lang="en">
<head>

     {%load static%}
     <link rel="stylesheet" type="text/css" href="{% static 'flashcards/css.css' %}">
     <link rel="stylesheet" type="text/css" href="{% static 'flashcards/add_note.css' %}">
     <meta charset="UTF-8">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <title>Document</title>
</head>
<body>


     <style>



     </style>


     
          {% block content %}


          <div class="text-container">

               <h1>Add Notes to {{ deck.title }}</h1>
       
           </div>

        



          <form method="post" action="{% url 'flashcards:add_notes' deck.id %}">

          {% csrf_token %}

          {{ form.as_p }}

          <button type="submit">Add Notes</button>

          </form>



          <a href="{% url 'flashcards:view_deck' deck.id %}">Back to Deck</a>

          {% endblock %}

</body>
</html>

templates/flashcards/create_card.html
<!DOCTYPE html>

<html lang="en">

<head>

    <meta charset="UTF-8">

    <title>Create Flashcard</title>

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'flashcards/css.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'flashcards/create_deck.css' %}">

</head>

<body>

    <div class="text-container">

        <h1>Create Card</h1>

    </div>


    <div class="main-content">

        <nav>
    
          <div class="row">
    
            <a href="{% url 'flashcards:user_profile' request.user.pk %}">Your Profile</a>

            <a href="{% url 'flashcards:flashcards_home' %}">Home</a>
    
    
          </div>
    
        </nav>


    <form method="post">

        {% csrf_token %}

        {{ form.as_p }}

        <button type="submit">Create Card</button>

    </form>

</body>

</html>

templates/flashcards/create_deck.html
<!DOCTYPE html>

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'flashcards/css.css' %}">

<link rel="stylesheet" type="text/css" href="{% static 'flashcards/create_deck.css' %}">




<html lang="en">

<head>

    <meta charset="UTF-8">

    <div class="text-container">

        <h1>Create Deck</h1>

    </div>

</head>

<body>


    <div class="main-content">

        <nav>
    
          <div class="row">
            <a href="{% url 'flashcards:user_profile' request.user.pk %}">Your Profile</a>
            <a href="{% url 'flashcards:flashcards_home' %}">Home</a>
          </div>

        </nav>



    <form method="post">

        {% csrf_token %}

        {{ form.as_p }}

        <button type="submit">Create Deck</button>

    </form>


</body>

</html>

templates/flashcards/edit_card.html
{%load static%}
<link rel="stylesheet" type="text/css" href="{% static 'flashcards/css.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'flashcards/create_deck.css' %}">


<div class="text-container">
 
     <h1>Edit Card</h1>

 </div>



<div class="main-content">
<form method="post">

    {% csrf_token %}

    {{ form.as_p }}

    <button type="submit">Save Changes</button>

</form>

</div>

templates/flashcards/flashcards_home.html
<!DOCTYPE html>

<html lang="en">


    {% load static %}


    <link rel="stylesheet" type="text/css" href="{% static 'flashcards/css.css' %}">


    <div class="text-container">

        <h1>Flashcardzz</h1>

    </div>


<body>

    {% if request.user.is_authenticated %}


    <div class="main-content">

        <nav>
    
          <div class="row">
    
            <a href="{% url 'flashcards:logout'%}">Log out</a>
    
          </div>
    
          <div class="row">
    
            <a href="{% url 'flashcards:user_profile' request.user.pk %}">Your Profile</a>

            <a href="{%url 'flashcards:flashcards_home'%}">/flashcards</a>

            <a href="{% url 'home_page:home_page'%}">App Depo</a>
    
          </div>
    
          <div class="row">
    
            <a href="{% url 'flashcards:clep'%}">CLEP</a>
    
          </div>
    
        </nav>


    {% else %}

    <div class="main-content">

        <nav>
    
          <div class="row">
    
            <a href="{% url 'flashcards:about_us'%}">About Us</a>
    
          </div>
    
          <div class="row">
    
            <a href="{% url 'flashcards:clep'%}">CLEP</a>
    
          </div>
    
        </nav>
    
    {% endif %}



    {% if request.user.is_authenticated %}

        <div class="hero">

        <p>Thank you for your support!</p>
            
        </div>
    {% else %}

        <div class="list-container">

        <div class="hero">

            <h2>Welcome to our platform!</h2>

            <ul>
      
            <li><p>Accelerate your learning with personalized flashcards.</li>

            <li><p> Create and share, then watch knowledge stick!</p></li>

            </ul>

            </div>

        </div>
       
        </div>

    {%endif%}


    
 
    
    </head>
    
    <body>
    
        <div class="grid-container">
    
            {% for category, decks in public_decks_by_category.items %}

            {% if decks%}
    
                <div class="grid-item">
    
                    <p>{{ category }}</p>
    
                    <ul>
    
                        {% for deck in decks %}
    
                            <li>
    
                                <a href="{% url 'flashcards:view_deck' deck.id %}">{{ deck.title }}</a>
    
                            </li>
    
                        {% endfor %}
    
                    </ul>
    
                </div>

            {%endif%}
    
            {% endfor %}
    
        </div>


      </br></br>
    
    
    

    </body>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/masonry/4.2.2/masonry.pkgd.min.js"></script>
    

    <script src="{% static 'javascript.js' %}"></script>
    
    </html>
    
    

templates/flashcards/flashcards_user_profile.html
<!DOCTYPE html>


{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'flashcards/css.css' %}">

<html lang="en">

<head>

    <meta charset="UTF-8">

    <div class="text-container">

        <h1>{{user}}</h1>

    </div>

</head>

<body>

    {% if user == request.user %}

    <div class="main-content">

        <nav>
    
          <div class="row">
    
            <a href="{% url 'logout'%}">Log out</a>
    
          </div>
    
          <div class="row">
    
            <a href="{% url 'flashcards:flashcards_home' %}">Home</a>
    
          </div>
    
          <div class="row">
    
            <a href="{% url 'flashcards:create_deck'%}">New Deck</a>
    
          </div>
    
        </nav>

    {%endif%}

    {% if request.user.is_authenticated %}

    {% if user != request.user %}

    <div class="main-content">

        <nav>
    
          <div class="row">
    
            <a href="{% url 'logout'%}">Log out</a>
    
          </div>
    
          <div class="row">
    
            <a href="{% url 'flashcards:flashcards_home' %}">Home</a>
    
          </div>
    
          <div class="row">
    
            <a href="{% url 'flashcards:user_profile' request.user.pk %}">Your Profile</a>
    
          </div>
    
        </nav>

    {%endif%}

    {%endif%}



 


    <div class="grid-container">
    {% for deck in user_decks %}

    <div class="grid-item">

        <p>{{deck.category}}</p>

        <ul>


        <li>

            {% if user == request.user %}

            <a href="{% url 'flashcards:edit_deck' deck.id%}">edit➯</a>

            {%endif%}
            
            <a href="{% url 'flashcards:view_deck' deck.id %}">{{ deck.title     }}</a>




        </li>
        </ul>
        </div>

    {% endfor %}
    </div>


</body>

<script src="https://cdnjs.cloudflare.com/ajax/libs/masonry/4.2.2/masonry.pkgd.min.js"></script>
    
<script src="{% static 'javascript.js' %}"></script>

</html>

templates/flashcards/view_deck.html
<!DOCTYPE html>

<html lang="en">

{% load static %}



<link rel="stylesheet" type="text/css" href="{% static 'flashcards/css.css' %}">


<link rel="stylesheet" type="text/css" href="{% static 'flashcards/view_deck.css' %}">



<head>

    <meta charset="UTF-8">

    <title>{{ deck.title }}</title>

    <div class="text-container">

        <h1>{{deck.title}}</h1>

    </div>

    <p class="admintag">Made by:{{deck.user}}</p>

</head>



<body>

    <div class="main-content">

        <nav>

            {% if deck.user == request.user %}

            <div class="row">

                <a href="{% url 'flashcards:create_card' deck.id %}">Create a New Card</a>

            </div>

            <div class="row">

                <a href="{% url 'flashcards:flashcards_home' %}">Go Home</a>

                <a href="{%url 'flashcards:add_notes' deck.id%}">Add Note</a>

                <a href="{% url 'flashcards:user_profile' request.user.pk %}">Your Profile</a>

            </div>

            <div class="row">

                <a href="{% url 'flashcards:edit_deck' deck.id %}">Edit Deck</a>

            </div>

            </nav>

            {% endif %}



            {% if request.user and request.user != deck.user and not request.user.is_anonymous %}

            <nav>

                <div class="row">

                    <a href="{% url 'flashcards:flashcards_home' %}">Go Home</a>

                    <a href="{% url 'flashcards:user_profile' request.user.pk %}">Your Profile</a>

                </div>

            </nav>

            {% endif %}



            {% if request.user.is_anonymous %}

            <nav>

                <div class="row">

                    <a href="{% url 'flashcards:flashcards_home' %}">Go Home</a>

                </div>

            </nav>

            {% endif %}


            <style>





.card-front {

background-image: url("{{ flashcard.image.url }}");

border-radius: 5%;


}



.card-back {

  border-radius: 5%;
  background-image:url("{{ back.image.url }}");

transform: rotateY(180deg);

}
    
          </style>


<div class="card-position">
          
            {% for card in cards %}

            <div class="card-container" id="card-{{ card.id }}">

              <p>Card {{ forloop.counter}}:</p>



                    <div class="card-inner">

                        <div class="card-front">

                            

                            <div id="content-{{ card.id }}" class="card-front">

                                <p class="question">{{ card.question }}</p>

                            </div>

                        </div>

                        <div class="card-back">

                            <p class="answer">{{ card.answer }}</p>

                        </div>

                

                </div>



                <div class="navmenu">

                    <div class="row">

                    <button onclick="showPrevious()"><img src="{{ left.image.url }}" alt="flip"></button>

                    <button onclick="flipCard({{ card.id }})"><img src="{{ flip_button.image.url }}" alt="flip"></button>

                    <button onclick="showNext()"><img src="{{ right.image.url }}" alt="flip"></button>

                    </div>

                    <form method="post" action="{% url 'flashcards:view_deck' deck.id %}">

                      {% csrf_token %}
  
                      <input type="hidden" name="card_id" value="{{ card.id }}">
  
                      {% if deck.user == request.user %}
  
                      <button type="submit" name="action" value="delete_card" class="deletebutton">Delete Card</button>
                      
                      {% endif %}


                      
                        {% if deck.user == request.user %}

                        

                        <a href="{% url 'flashcards:edit_card' card.id %}" class="edit-link">Edit Card</a>
        
                        {% endif %}


                </div>
                   

                </form>



            </div>

            {% endfor %}

          </div>

          </div>




            <div class="center-content">


          <div class="note-container">
            <h2>Notes:</h2>

        
            {% for note in notes %}
            <div class="center-notes">
               
            
            <p>{{ note.date|date:"F d, Y" }}</p>

            <ul>
        
            <li><div class="notes-style">{{ note.note }}</div></li>
        </ul>

        <div class="center-notes">

 
            {% if note.user == request.user %}

            
 
                <a href="{% url 'flashcards:edit_note' note.id %}" class="edit-link">Edit Note</a>
 
            {% endif %}
 
        </div>
   
        
    </div>
                
        
            {% endfor %}

        </div>

        </div>


            <script>

                var currentCardIndex = 0;

                var cards = document.querySelectorAll('.card-container');



                function showCard(index) {

                    cards.forEach(function (card, i) {

                        card.classList.remove('flipped');

                        card.style.display = (i === index) ? 'block' : 'none';

                    });

                }



                function showNext() {

                    currentCardIndex = (currentCardIndex + 1) % cards.length;

                    showCard(currentCardIndex);

                }



                function showPrevious() {

                    currentCardIndex = (currentCardIndex - 1 + cards.length) % cards.length;

                    showCard(currentCardIndex);

                }



                function flipCard(cardId) {

                    var cardContainer = document.getElementById('card-' + cardId);

                    cardContainer.classList.toggle('flipped');

                }


                showCard(currentCardIndex);

            </script>

</body>

</html>