home_page/urls.py
from django.urls import path, include


from django.contrib.auth import views as auth_views
from django.contrib import admin

from django.conf.urls.static import static
from django.conf import settings

from . import views

app_name='home_page'

urlpatterns = [
    path("", views.home, name="home_page"),
    

    
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ilovecookbooks/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



from django.urls import path, include
from . import views
from .views import blogview, videopage, BookDetailView,UserProfileView
from django.conf.urls import *
from django.urls import path 
from django.contrib import admin



app_name= "ilovecookbooks"

urlpatterns = [
    path("ilovecookbooks", views.Main, name="Main"),

    path("ilovecookbooks2", views.Main, name="Home"),

    path('ilovecookbooks/foodblog/', blogview.as_view(), name="foodblog"),

    path('ilovecookbooks/details/<int:pk>', videopage.as_view(), name='details'),

    path('ilovecookbooks/book/<int:pk>/', BookDetailView.as_view(), name='book_detail'),
    
    path('ilovecookbooks/links/', views.link_view, name='links'),

    path('ilovecookbooks/base/', views.base, name='base'),

    path('ilovecookbooks/search/', views.search_results, name='search_results'),


    path('ilovecookbooks/profile/<int:pk>/', views.UserProfileView, name='user_profile'),

    path('ilovecookbooks/user_books/<int:user_book_id>/', views.user_book_pages, name='user_book_pages'),

    path('ilovecookbooks/page/<int:page_id>/book/<int:book_id>/', views.page_view, name='page_view'),

    path('ilovecookbooks/default_profile_images/<int:pk>/', views.default_profile_images, name='default_profile_images'),

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profiles/urls.py
from django.urls import path, include

from . import views

app_name='profiles'

urlpatterns=[

     path('user_profile/', views.user_profile, name='User_Profile'),

     path('login/', views.login_the_user, name='login'),

     path('register/', views.registration, name='register'),

     

]

theappdepo/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static



urlpatterns=[
     
    path("", include("home_page.urls")),
     
    path('', include('profiles.urls')),

    path('', include('experimental_playground.urls')),

    path('', include("ilovecookbooks.urls")),

    path('', include("flashcards.urls")),


     path('admin/',admin.site.urls),

     path('accounts/', include('django.contrib.auth.urls')),

     path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),

     path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),

     path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_done'),

     path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

     path('logout', auth_views.LogoutView.as_view(), name='logout'),

     

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ilovecookbooks/forms.py
from django import forms
from .models import UserBook

from django.contrib.auth import get_user_model



class SavePageForm(forms.Form):

    def __init__(self, user, *args, **kwargs):

        super(SavePageForm, self).__init__(*args, **kwargs)

        self.fields['user_book'].queryset = UserBook.objects.filter(user=user)



    user_book = forms.ModelChoiceField(queryset=UserBook.objects.none(), empty_label=None, label="Select User Book")



class UserBookForm(forms.ModelForm):

    class Meta:

        model = UserBook

        fields = ['title']

class DeleteUserBookForm(forms.Form):

    def __init__(self, user, *args, **kwargs):

        super(DeleteUserBookForm, self).__init__(*args, **kwargs)

        self.fields['user_book'].queryset = UserBook.objects.filter(user=user)


    user_book = forms.ModelChoiceField(queryset=UserBook.objects.none(), empty_label=None, label="Select User Book")

class DeleteUserBookPageForm(forms.Form):

    user_book_page_id = forms.IntegerField(widget=forms.HiddenInput())


from .models import DefaultUserProfilePicture
    
from django import forms



class UserProfilePicChangeForm(forms.Form):

    user_pic = forms.ImageField(label='Upload a new profile picture', required=False)

ilovecookbooks/views.py
from django.views.generic import ListView, DetailView
from django.views import generic
from django.urls import reverse_lazy
from django.views.generic import DetailView 
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect, get_object_or_404, HttpResponseRedirect

from django.contrib.auth import get_user_model

from django.core.mail import send_mail
from django.conf import settings
from django.views import View 
from .models import Book, Post, BookPage,UserBook, UserBookPage, BookPage, DefaultUserProfilePicture
from django.http import HttpResponse
from django.contrib import messages
from .forms import UserBookForm, DeleteUserBookForm,DeleteUserBookPageForm ,UserProfilePicChangeForm, SavePageForm
from django.http import HttpResponseForbidden

CLOUDFRONT_URL='https://d17usxoyp786nd.cloudfront.net/'


def Main(request):

    recent5 = Book.objects.order_by('-id')[:5]  # Order by id in descending order to get the latest 5 books

    all_books = Book.objects.all()

    pages = BookPage.objects.all()

    context = {

        'recent': recent5,

        'pages': pages,

        'all': all_books,

        'cloudfront_url':CLOUDFRONT_URL,

    }

    return render(request, 'ilovecookbooks_home.html', context)


def base(request):
        

        recent5 = Book.objects.order_by('-id')[:5]
        
        all= Book.objects.all()
        
        pages=BookPage.objects.all()

        context = {
        'all'   : all,
        'recent': recent5,
        'pages' : pages,
        'cloudfront_url':CLOUDFRONT_URL,
    }
        return render(request, 'base.html',context)


def link_view(request): 
    a = Book.objects.filter(title__istartswith='a').order_by('title')
    b = Book.objects.filter(title__istartswith='b').order_by('title')
    c = Book.objects.filter(title__istartswith='c').order_by('title')
    d = Book.objects.filter(title__istartswith='d').order_by('title')
    e = Book.objects.filter(title__istartswith='e').order_by('title')
    f = Book.objects.filter(title__istartswith='f').order_by('title')
    g = Book.objects.filter(title__istartswith='g').order_by('title')
    h = Book.objects.filter(title__istartswith='h').order_by('title')
    i = Book.objects.filter(title__istartswith='i').order_by('title')
    j = Book.objects.filter(title__istartswith='j').order_by('title')
    k = Book.objects.filter(title__istartswith='k').order_by('title')
    l = Book.objects.filter(title__istartswith='l').order_by('title')
    m = Book.objects.filter(title__istartswith='m').order_by('title')
    n = Book.objects.filter(title__istartswith='n').order_by('title')
    o = Book.objects.filter(title__istartswith='o').order_by('title')
    p = Book.objects.filter(title__istartswith='p').order_by('title')
    q = Book.objects.filter(title__istartswith='q').order_by('title') 
    r = Book.objects.filter(title__istartswith='r').order_by('title')
    s = Book.objects.filter(title__istartswith='s').order_by('title')
    t = Book.objects.filter(title__istartswith='t').order_by('title')
    u = Book.objects.filter(title__istartswith='u').order_by('title')
    v = Book.objects.filter(title__istartswith='v').order_by('title')
    w = Book.objects.filter(title__istartswith='w').order_by('title')
    x = Book.objects.filter(title__istartswith='x').order_by('title')
    y = Book.objects.filter(title__istartswith='y').order_by('title')
    z = Book.objects.filter(title__istartswith='z').order_by('title')


    context = { 'a': a,
               'b': b,
               'c': c,
               'd':d,
               'e' :e, 
               'f' :f, 
               'g' :g, 
               'h' :h, 
               'i' :i, 
               'j' :j, 
               'k' :k, 
               'l' :l, 
               'm' :m,
               'n' :n, 
               'o' :o, 
               'p' :p,   
               'q' :q, 
               'r' :r, 
               's' :s, 
               't' :t, 
               'u' :u, 
               'v' :v, 
               'w' :w, 
               'x' :x, 
               'y' :y, 
               'z' :z, 
               } 
    return render(request, 'links.html', context)


#def search_results(request):
#
#    search_term = request.GET.get('search_term')
#    if search_term:
#        search_results = BookPage.objects.filter(keywords__contains=search_term)
#    else:
#        search_results = None
#    
#    context = {'search_results': search_results}
#    return render(request, 'search_results.html', context)


class BookDetailView(DetailView):
    model = Book
    template_name = 'book_detail.html'
    context_object_name = 'book'


class blogview(ListView):
    model = Post
    template_name = 'another_template.html'


class videopage(DetailView):
    model = Post
    template_name = 'videoclass.html'


def search_results(request):

    search_term = request.GET.get('search_term')

    search_results = []

    if search_term:

        search_results = BookPage.objects.filter(keywords__contains=search_term)

        MEDIA_UR='https://d17usxoyp786nd.cloudfront.net/'
        

    context = {'search_results': search_results, 'MEDIA_URL': MEDIA_UR}

    return render(request, 'search_results.html', context)




def UserProfileView(request, pk):

    user_model = get_user_model()

    user_profile = user_model.objects.get(pk=pk)

    user_image_url= user_profile.ilovecookbooks_profile_pic.url

    user_books = UserBook.objects.filter(user=user_profile)

    delete_form = DeleteUserBookForm(request.user, request.POST if request.method == 'POST' else None)

    create_form = UserBookForm()


    if request.method == 'POST':

        if 'create_book' in request.POST:

            if user_books.count() >= 12:

                return redirect(request.path_info)  # Redirect to the user's profile page

            create_form = UserBookForm(request.POST)

            if create_form.is_valid():

                user_book = create_form.save(commit=False)

                user_book.user = request.user

                user_book.save()

                return HttpResponseRedirect(request.path_info)

        elif 'delete_book' in request.POST:

            user_book_id = request.POST.get('user_book', None)

            if user_book_id:

                user_book = UserBook.objects.filter(user=request.user, id=user_book_id).first()

                user_book.delete()

                return HttpResponseRedirect(request.path_info)

                # Handle delete action (e.g., user_book.delete())



    context = {
        'profile_image':user_image_url,

        'user_profile': user_profile,

        'user_books': user_books,

        'delete_form': delete_form,

        'create_form': create_form,

    }

    

    return render(request, 'ilovecookbooks_profile.html', context)

def user_book_pages(request, user_book_id):

    user_book = get_object_or_404(UserBook, id=user_book_id)

    user_book_pages = user_book.userbookpage_set.all().order_by('order')

    if request.method == 'POST':

        delete_form = DeleteUserBookPageForm(request.POST)

        if delete_form.is_valid():

            user_book_page_id = delete_form.cleaned_data['user_book_page_id']

            user_book_page = get_object_or_404(UserBookPage, id=user_book_page_id)

            # Check if the logged-in user is the owner of the user book

            if user_book.user == request.user:

                user_book_page.delete()

            else:

                return HttpResponseForbidden("You are not the owner of this user book, so you can't delete pages.")

    else:

        delete_form = DeleteUserBookPageForm()


    context = {

        'user_book': user_book,

        'user_book_pages': user_book_pages,

        'delete_form': delete_form,

    }

    return render(request, 'user_books.html', context)


def page_view(request, page_id, book_id):

    page = get_object_or_404(BookPage, pk=page_id)

    book = get_object_or_404(Book, pk=book_id)


    if request.method == 'POST':

        form = SavePageForm(user=request.user, data=request.POST)

        if form.is_valid():

            user_book = form.cleaned_data['user_book']

            user_book_page, created = UserBookPage.objects.get_or_create(

                user_book=user_book,

                book_page=page

            )

            if created:

                return redirect('ilovecookbooks:book_detail', pk=book.id)

            else:

                return HttpResponse("Page was not saved. I'm sorry :'(")

    else:

        form = SavePageForm(user=request.user)  # Pass the user as an argument here

    context = {

        'page': page,

        'book': book,

        'form': form,

    }

    return render(request, 'page_view.html', context)


def default_profile_images(request,pk):
    
    user_model = get_user_model()


    user_profile = user_model.objects.get(pk=pk)

    
    if request.method == 'POST':

        form = UserProfilePicChangeForm(request.POST, request.FILES)

        if form.is_valid():


            default_pic_id = request.POST.get('default_pic')
            print(default_pic_id)

            if default_pic_id:

                print('DEFAULT WAS SELECTED')

                default_pic = DefaultUserProfilePicture.objects.get(pk=default_pic_id)

                user_profile.ilovecookbooks_profile_pic = default_pic.image

                user_profile.save()

            else:
   
                if 'user_pic' in request.FILES:

                    print("USER PICTURE UPLOADED")

                    user_profile.ilovecookbooks_profile_pic = form.cleaned_data['user_pic']

                    user_profile.save()

            return redirect('ilovecookbooks:default_profile_images', pk=user_profile.pk)

    else:

        form = UserProfilePicChangeForm()

    default_pics = DefaultUserProfilePicture.objects.all()

    context = {

        'user_profile': user_profile,

        'form': form,

        'default_pics': default_pics,

    }

templates/ilovecookbooks/another_template.html
<div class="titlelabel">

<h1>Videos</h1>

</div>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'ILOVECOOKBOOKS/css.css' %}">

{% for post in object_list %}
<div class="column2">
    <div class="object">

        <div class="videotitle">
            Author: {{post.author}}<br/>
    
        </div>
        <div class="videotitles2">
            {{post.title}} <br>
    
        </div>
        <div class="videotitles3">
    {{post.body}}
    </div>
    <div class="thumbnail">
    <img src="{{ post.thumbnail.url }}" alt="{{ post.title }}">
    </div>
    <a href="{% url 'ilovecookbooks:details' post.pk %}">view video</a>
</div>

</div>

{% endfor %}

<div class="homebutton">
    <a href="{% url 'ilovecookbooks:base' %}">Home</a>
</div>

templates/ilovecookbooks/base.html
<!DOCTYPE html>

<html lang="en">

<head>

    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'ilovecookbooks/css.css' %}">

    <div id="header">

        {% if user.is_authenticated %}
         <h1>Welcome {{user.username}}</h1>
        {% else %}
            <h1>Welcome!</h1>
        {% endif%}




    </div>

</head>

<body>

    <body onload="loadHeader()">

        <div id="header"></div>

    <div id="topbarbackcolor">

    <div class="flexbox-container">

        <div class="flexbox-item flexbox-item-1"><a href="{% url 'ilovecookbooks:foodblog' %}">Food Blog</a></div>

        <div class="flexbox-item flexbox-item-2"><a href="{% url 'ilovecookbooks:links' %}">Book Links</a></div>

        <div class="flexbox-item flexbox-item-1"><a href="{% url 'home_page:home_page' %}">App Depo</a></div>


        {% if user.is_authenticated %}

        {% with user_profile=user.userprofile %}
    
            <div class="flexbox-item flexbox-item-2">
    
                <a href="{%url 'ilovecookbooks:user_profile' user.pk%}">Your Stuff</a>            
    
            </div>
    
        {% endwith %}
    
        {% else %}
    
            <div class="flexbox-item flexbox-item-2">
        
                <a href="{% url 'profiles:login' %}">Login/Register</a>
        
            </div>
        
        {% endif %}
    
    

        <form id="search-form" action="{% url 'ilovecookbooks:search_results' %}" method="get">

            <input class="flexbox-item-entrybox" type="text" name="search_term" autocomplete="off" autofocus="true">

        </form>

        <form id="search-button" action="{% url 'ilovecookbooks:search_results' %}" method="get">

            <button class="flexbox-item-button" type="submit">Search</button>

        </form>

    </div>



    <div class="titlelabel">

    <h3>Recently Uploaded</h3>

    </div>



    <div class="carousel-container4">

        <div class="flexbox-container3">



            {% for book in recent %}

                <div class="book-item">

                    <strong>Title:</strong> {{ book.title }}<br>

                    <strong>Year:</strong> {{ book.year }}<br>

                    {% if book.cover_photo %}

                        <div class="book-image">

                            <!-- Use a local path for the image source -->

                            <img src="{{ book.cover_photo.url }}" alt="Page {{ page.pk }}">  

                        </div>

                    {% else %}

                        No image available<br>

                    {% endif %}

                    <a href="{% url 'ilovecookbooks:book_detail' pk=book.pk %}">View Details</a>

                </div>

            {% endfor %}



        </div>

    </div>



    <div class="titlelabel">

        <h3>All Books</h3>

    </div>

    

    <div class="carousel-container4">

        <div class="flexbox-container3">


            {% for book in all %}

                <div class="book-item">

                    <strong>Title:</strong> {{ book.title }}<br>

                    <strong>Year:</strong> {{ book.year }}<br>

                    {% if book.cover_photo %}

                        <div class="book-image">

                            <img src="{{ book.cover_photo.url }}" alt="Page {{ page.pk }}">  

                        </div>

                    {% else %}

                        No image available<br>

                    {% endif %}

                    <a href="{% url 'ilovecookbooks:book_detail' pk=book.pk %}" alt="Not Found">View Details</a>

                    

                </div>

            {% endfor %}


        </div>

    </div>

</body>




<script>

    document.addEventListener('DOMContentLoaded', function() {
    
    
    
        var searchForm = document.getElementById('search-form');
    
        var searchInput = searchForm.querySelector('[name="search_term"]');
    
        var searchButton = document.getElementById('search-button');
    
    
        searchForm.addEventListener('submit', function(event) {
    
            event.preventDefault(); // Prevent the form from submitting normally
    
            
    
            var searchTerm = searchInput.value.toLowerCase(); // Convert input to lowercase
    
            
    
            if (searchTerm.trim() !== '') {
    
                window.location.href = "{% url 'ilovecookbooks:search_results' %}?search_term=" + encodeURIComponent(searchTerm);
    
            }
    
        });
    
        searchButton.addEventListener('click', function(event) {
    
            event.preventDefault(); // Prevent the button from performing its default action
    
            searchForm.dispatchEvent(new Event('submit')); // Trigger the form submit event
    
        });
    
    });
    
    </script>




<body onload="loadHeader()">
    <div id="header"></div>
  
    <script>
      function loadHeader() {
        // No need to do anything here, the animation starts automatically
      }
    </script>

templates/ilovecookbooks/book_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'ilovecookbooks/css.css' %}">
    <title>{{ book.title }} Details</title>
</head>
<body>

    <style>

        .detaillink{

            padding-top: 30px;
        }

        .homelink{

            background: linear-gradient(#D8D4BB, #8f8f8f);
            width: fit-content;
            padding:10px;

            border-radius: 10px 10px 10px 10px; /* Rounded corners on top */
        
        }
    </style>

    <div class="carousel-container4">
        <div class="flexbox-container3">

            {% for page in book.pages.all %}

            <div class="book-item">
            
                {% if page.page_photo %}
            
                <div class="page-image">
            
                    <img src="{{ page.page_photo.url }}" alt="Page {{ page.pk }}">
            
                </div>
                

                <div class="detaillink">
            
                <strong><a href="{% url 'ilovecookbooks:page_view' page.id book.id %}">Details</a></strong>

                </div>
            
                {% else %}
            
                No image available<br>
            
                {% endif %}
            
            </div>
            
            {% endfor %}
            
            
        </div>
    </div>
</div>

<div class="homelink">
<a href="{% url 'ilovecookbooks:Home' %}">Go Home</a>
</div>

</body>
</html>

templates/ilovecookbooks/default_profile_images.html
<!DOCTYPE html>

<html>

<head>

    <title>Change Profile Picture</title>
    {% load static %}

    <style>

        body {

            font-family: Arial, sans-serif;

            background: linear-gradient(#646257, #2e2c2c, #646257);

            text-align: center;

        }

        h1 {

            color: #007bff;

        }

        img {

            max-width: 100%;

            height: auto;

        }

        form {

            margin: 20px;

        }

        ul {

            list-style: none;

            padding: 0;

            display: grid;

            grid-template-columns: repeat(5, 1fr);

            grid-gap: 20px;

            justify-items: center;

        }

        li {

            text-align: center;

        }

        .homelink{

        background: linear-gradient(#D8D4BB, #8f8f8f);
        width: fit-content;
        padding:10px;

        border-radius: 10px 10px 10px 10px; /* Rounded corners on top */

        }

    </style>

</head>

<body>

    <h1>Change Profile Picture</h1>

    <img src="{{ user.ilovecookbooks_profile_pic.url}}" alt="User Profile Picture">

    <form method="post" enctype="multipart/form-data">

        {% csrf_token %}

        {{ form.as_p }}

        <input type="submit" value="Change Profile Picture">

    </form>

    <div class="homelink"><a href="{% url 'ilovecookbooks:Home' %}">Go Home</a></div>

    <h2>Choose a Default Profile Picture</h2>

    <ul>

        {% for pic in default_pics %}

            <li>

                <img src="{{ pic.image.url }}" alt="{{ pic.name }}">

                <form method="post" action="{% url 'ilovecookbooks:default_profile_images' pk=user_profile.pk %}">

                    {% csrf_token %}

                    <input type="hidden" name="default_pic" value="{{ pic.id }}">

                    <input type="submit" value="Set as Profile Picture">

                </form>

            </li>

        {% endfor %}

    </ul>

</body>

</html>

templates/ilovecookbooks/ilovecookbooks_profile.html
<!DOCTYPE html>

<html lang="en">

<head>

    {%load static%}

    <title>User Profile</title>

    <link rel="stylesheet" type="text/css" href="{% static 'ilovecookbooks/css.css' %}">

    <style>




        .flexbox-container {

            display: flex;

            justify-content: space-between;

            align-items: center;

            background: linear-gradient(#ffdd0000 73%, #D8D4BB 27%);


        }



        .flexbox-item {

            margin: 0;

        }



        .change-photo-link,

        .logout-button,

        .home-link {

            margin-left: 10px;

        }



        .profile-container {

            width: 100%;

            margin: 0 auto;

            background: linear-gradient(#D8D4BB, #8f8f8f);

            border: 1px solid #ddd;

            border-radius: 5px;

            display: flex;

            flex-direction: row;

            align-items: flex-start;

            justify-content: space-between;

            padding: 20px;

        }



        .user-info {

            text-align: left;

        }



        .user-pic {

            width:25%;

            max-width: 65%;

            height: auto;

        }



        .user-pic img {

            height: 30%;

        }



        .user-books {

            flex: 1;

            padding-left: 15%;

            padding-top: 10%;

            text-align: left;

        }



        .books-list {

            list-style: none;

            padding: 0;

            text-align: left;

        }



        .books-list li {

            margin: 10px 0;

        }



        .form-container {

            display: grid;

            grid-template-columns: 1fr 1.5fr;

            align-items: left;

            position: sticky;
            

        }



        .create-book-form,

        .delete-book-form {

            margin: 20px 0;

        }



        .button {

            background-color: #007bff;

            color: #fff;

            border: none;

            padding: 10px 20px;

            border-radius: 5px;

            cursor: pointer;

        }

        .button2 {

            background-color: #007bff00;

            color: #007bff;

            font-size: large;
            font-weight: bold;


            border: none;

            padding: 10px 20px;

            border-radius: 5px;

            cursor: pointer;

            }



        .button:hover {

            background-color: #0056b3;

        }



        a {

            text-decoration: none;

            color: #007bff;

        }



        a:hover {

            text-decoration: underline;

        }

    </style>



<form method="post" action="{% url 'logout' %}">

</head>

<body>

    <div class="flexbox-container">

        <div class="flexbox-item flexbox-item-2">

            <a href="{% url 'ilovecookbooks:links' %}">Book Links</a>

        </div>



        {% if user == request.user %}

            <div class="flexbox-item flexbox-item-2">

                <a class="change-photo-link" href="{% url 'ilovecookbooks:default_profile_images' user.pk %}">Change Photo</a>

            </div>

        {% endif %}



        <div class="flexbox-item flexbox-item-2">

            <a href="{% url 'ilovecookbooks:Home' %}" class="home-link">Go Home</a>

        </div>



        <div class="flexbox-item flexbox-item-2">

            <form method="post" action="{% url 'logout' %}">

                {% csrf_token %}

                <button class="button2 logout-button" type="submit">Logout</button>

            </form>

        </div>

    </div>



    <div class="profile-container">

        <div class="user-info">

            <h1>User Profile</h1>

            <p><strong>Username:</strong> {{ user.username }}</p>



            <div class="user-pic">

                <img src="{{ profile_image }}" alt="User Profile Pic">

            </div>

        </div>





        <div class="form-container">

            <div class="create-book-form">

                <h2>Create a New User Book:</h2>

                <form method="post">

                    {% csrf_token %}

                    {{ create_form.as_p }}

                    <button class="button" type="submit" name="create_book">Create User Book</button>

                </form>

            </div>



            <div class="delete-book-form">

                <h2>Delete User Book:</h2>

                <form method="post">

                    {% csrf_token %}

                    {{ delete_form.as_p }}

                    <button class="button" type="submit" name="delete_book">Delete User Book</button>

                </form>

            </div>

            <div class="user-books">

                <h2>User's Books:</h2>
    
                <ul class="books-list">
    
                    {% for user_book in user_books %}
    
                        <li>
    
                            <a href="{% url 'ilovecookbooks:user_book_pages' user_book_id=user_book.id %}">{{ user_book.title }}</a>
    
                        </li>
    
                    {% endfor %}
    
                </ul>
    
            </div>

        </div>

    </div>

</body>

</html>

templates/ilovecookbooks/search_results.html
<!DOCTYPE html>

<html lang="en">

<style>

    .detaillink{

    padding-top: 30px;
    }

    .homelink{

        background: linear-gradient(rgb(123, 114, 56), #8f8f8f);

        width: fit-content;
        
        padding:10px;

        border-radius: 10px 10px 10px 10px; /* Rounded corners on top */

        }

</style>

<head>

    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'ilovecookbooks/css.css' %}">


</head>

<body>

    {% if search_results %}

    <div class="carousel-container4">

        <div class="flexbox-container3">

            {% for page in search_results %}

            <div class="book-item">

                <strong>Book Title:</strong> {{ page.book.title }}<br>

                <div class="page-image">

                    <img src="{{ MEDIA_URL }}{{ page.page_photo.name }}" alt="{{ page.book.title }}">

                </div>

                <div class="detaillink">
            
                    <strong><a href="{% url 'ilovecookbooks:page_view' page.id page.book.id %}">Details</a></strong>
    
                </div>
    

            </div>


            {% endfor %}

        </div>

    </div>

    {% else %}

    <p>No results found.</p>

    {% endif %}


    <div class="homelink"><a href="{% url 'ilovecookbooks:Home' %}">Go Home</a></div>

</body>

</html>

templates/ilovecookbooks/videoclass.html
<!DOCTYPE html>
<html>
<head>
    <div class="videotitles4">
    <title>Post Details</title>
   
    <h1>{{ post.title }}</h1>
    <small> By: {{ post.author}}</small><br>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'ilovecookbooks/css.css' %}">
</div>
    
</head>
<body>

<div class="videotitles5">
<div class="viewer">
<video class="viewer" controls>
    <source src="{{ post.video_file.url }}" type="video/mp4">
    Your browser does not support the video tag.
</video>
</div>
<div class="videotitles6">
    <div class="postbody">
<p>{{ post.body }}</p>
</div>
</div>
<p>Date: {{ post.date }}</p>
<div><a href="{% url 'ilovecookbooks:base' %}">Home</a></div>
<div class="videotitles5">



</div>
</div>


</body>
</html>